# Generated by Django 3.0.5 on 2020-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activestatus',
            field=models.CharField(blank=True, default='YES', max_length=100),
        ),
    ]
