# Generated by Django 3.0 on 2020-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200714_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isDoctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
