# Generated by Django 3.0.5 on 2020-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patiantFirstName', models.CharField(default='', max_length=90)),
                ('patiantLastName', models.CharField(default='', max_length=90)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(default='', max_length=30)),
                ('weight', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('nhsnumber', models.IntegerField(default=0)),
                ('insuranceid', models.CharField(default='', max_length=90)),
                ('pincode', models.CharField(default='', max_length=70)),
                ('fatherHusbandName', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('activestatus', models.CharField(default='', max_length=70)),
                ('patiantImage', models.CharField(default='', max_length=70)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
